load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "dir_maker.go",
        "opener.go",
    ],
    importpath = "github.com/autotelic/contentful-fetcher/lib/filesystem",
    visibility = ["//visibility:public"],
)
